mybatis:
    configuration:
        map-underscore-to-camel-case: true
        
spring:
   datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://35.200.101.90:3306/hyun
        username: hyun
        password: hyun1234
